### PR TITLE
Add support for non-singlteon services (definitions)

### PR DESCRIPTION
**Pull request by Khartir**
This adds support for services that are not defined as singletions (using the `definitions` key).
I also took the liberty to remove some unused code. If I was wrong about that, or you would rather have a separate PR for that I can remove it here.

### CODE REVIEW

**Comment by Khartir** [comment]
Hi. Anything I can do to help move this along?

**Comment by akondas** [comment]
For me looks ok, @marmichalski?

**Comment by marmichalski** [comment]
Thanks 👍

**Comment by akondas** [comment]
new release?

**Comment by marmichalski** [comment]
0.7.3 has been released 🥇

**Comment by akondas** [comment]
Perfect :muscle:

**Pull request merged**
