### PR TITLE
Check RHS string container definition against class_exist() first

### LINKED ISSUE #37: String service definitions are considered function
For entry
```php
[
    'singletons' => [
        CacheInterface::class => FileCache::class
    ]
]
```
in container configurations I get
```
In ServiceMap.php line 87:
                                                   
  Function yii\caching\FileCache() does not exist
```
because this service definition [is considered function](https://github.com/proget-hq/phpstan-yii2/blob/a24ea3f9bb02cfe4e6985cc3c18f0e3e5719fa58/src/ServiceMap.php#L82).

Probably adding 
```php
        if (\is_string($service) && class_exists($service)) {
            $this->services[$id] = $service;
            return;
        }
```
at the top of `addServiceDefinition()` is enough to resolve this problem.

### PR DESCRIPTION
**Pull request by przepompownia**
Closes #37

### CODE REVIEW

**Comment by akondas** [comment]
Thanks, there are some errors in static analysis (phpstan). Do you think you will be able to fix them?

**Comment by przepompownia** [comment]
Note that there are present in previous commit https://github.com/proget-hq/phpstan-yii2/runs/1750059336

**Comment by marmichalski** [comment]
Thanks! 🌹

**Comment by przepompownia** [comment]
Thank you too. Do you consider to issue a release to allow get it by tag from composer?

**Comment by marmichalski** [comment]
It has been tagged just about now: https://github.com/proget-hq/phpstan-yii2/releases/tag/0.7.4

**Pull request merged**
